#pragma once

#define TICK_INTERVAL 30
#define WIDTH 1092
#define HEIGHT 720
#define NUMBER_OF_CARS 7

#define SIZE_OF_SENSOR 80
#define FRONT_SENSOR_DISTANCE 0
#define FRONT_SENSOR_DEPTH 150
#define FULL_STOP_DISTANCE 100

#define CAR_SAFETY_DISTANCE 50

#define SW_ZOOM 2

#define TARGET_LINE_LENGTH 20
#define CAR_SIZE 10

